### ISSUE TITLE
Prepare this Tutorial for "Publication"

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-elm-architecture-in-javascript#29]
We need to be a _lot_ more systematic in how we _share_ the content we produce. 

## Todo

+ [ ] Tidy up the _content_ removing anything superfluous!
+ [ ] Produce the 5 min video
+ [ ] Prepare the tweet with link to video and image

## Question (_for Inês..._)

@iteles should we do our CMS/Blog MVP `before` _publicising_ this content so that we get SEO from it?

> The _reason_ I have not _previously_ prepared the "***Content Launch Checklist***" is because it requires a _chunk_ of work from _me_ where I tend to get pretty _exhausted_ from writing the _initial_ tutorial and just want to get "back" to my "real work" ... 😖  ⏳

**Comment by iteles** [comment]
Ideally, yes, but we need to set a deadline by which if we don't have the CMS/blog done, we publicise this anyway so it doesn't get forgotten.
Time to write up that detailed June plan!
