### ISSUE TITLE
Main Todo List View <section class="main">

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-elm-architecture-in-javascript#51]
The "Main" `view` in the Todo List Application displays the actual _list_.
Try it: http://todomvc.com/examples/vanillajs/
![todomvc-main-section-todo-list-html](https://user-images.githubusercontent.com/194400/43717480-9fb80982-997f-11e8-9ffe-6aa90a89a042.png)

This is the HTML copied directly from the browser:
```html
<section class="main" style="display: block;">
  <input class="toggle-all" type="checkbox">
  <label for="toggle-all">Mark all as complete</label>
  <ul class="todo-list">
    <li data-id="1533501855500" class="completed">
      <div class="view">
        <input class="toggle" type="checkbox">
        <label>Learn Elm Architecture</label>
        <button class="destroy"></button>
      </div>
    </li>
    <li data-id="1533501861171" class="">
      <div class="view">
        <input class="toggle" type="checkbox">
        <label>Build Todo List App</label>
        <button class="destroy"></button>
      </div>
    </li>
    <li data-id="1533501867123" class="">
      <div class="view">
        <input class="toggle" type="checkbox">
        <label>Win the Internet!</label>
        <button class="destroy"></button>
      </div>
    </li>
  </ul>
</section>
```

## Acceptance Criteria

+ [ ] Todo List items should be displayed as list items **`<li>`** in an _unordered list_ **`<ul>`**.
+ [ ] Each Todo List item **`<li>`**  should contain a **`<div>`** with a **`class="view"`** which "wraps":
  + [ ] **`<input class="toggle" type="checkbox">`** - the "checkbox" that people can "Toggle" to change the "state" of the Todo item from "active" to "done" (_which updates the model From: `model.todos[id].done=false` To: `model.todos[id].done=true`
  + [ ] **`<label>`** - the text content of the todo list item
  + [ ] **`<button class="destroy">`** - the button the person can click/tap to **`delete`** a Todo item.

Note: the "toggle-all" (_above the "main" list_) is a _separate_ issue/feature: https://github.com/dwyl/learn-elm-architecture-in-javascript/issues/50

This issue is part of the TodoMVC Feature List [Epic] #48

**Comment by nelsonic** [comment]
Test _first_: 
![image](https://user-images.githubusercontent.com/194400/43741630-f03f1fe8-99c6-11e8-8b7b-e44ee397b38e.png)

**Comment by nelsonic** [comment]
Rendering an individual todo list item (**`<li>`**) is handled by **`render_item`** see: #52
