### ISSUE TITLE
render_footer renders the <footer> element of Todo App

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-elm-architecture-in-javascript#53]
# Todo App `<footer>` Element

Referring to the _rendered_ HTML on http://todomvc.com/examples/vanillajs as our "guide":
![image](https://user-images.githubusercontent.com/194400/42633421-5eb20f24-85d8-11e8-94ad-bb653dd93ab0.png)
there is:
+ [x] a **`<footer>`** element with 
  + [x] a **`<span>`** element which contains 
    + [x] a **`text`** node with: **"`{count}` item(s) left"**.
  + [x] a **`<ul>`** containing 
    + [x] 3 **`<li>`** elements each with 
     + [x] a link (**`<a>`**) which allow the "user" to ***filter*** which items appear in the **`<view>`**.
  + [x] a **`<button class="clear-completed">`** which will **_Clear_ all `Completed`** items when clicked.

##  Dev Tools > Elements (inspector) 

![todo-list-mvc-](https://user-images.githubusercontent.com/194400/43768735-f1f7798e-9a2f-11e8-9f73-c69ea63b1064.png)

### Copy-paste the _rendered_ HTML

I "_copy-pasted_" of the _rendered_ HTML from the Dev Tools:
![todo-list-mvc-copy-html](https://user-images.githubusercontent.com/194400/43769759-6f18ca4c-9a32-11e8-8f96-7b19ed364c07.png)

```html
<footer class="footer" style="display: block;">
  <span class="todo-count">
    <strong>2</strong> items left
  </span>
  <ul class="filters">
    <li>
      <a href="#/" class="selected">All</a>
    </li>
    <li>
      <a href="#/active">Active</a>
    </li>
    <li>
      <a href="#/completed">Completed</a>
    </li>
  </ul>
  <button class="clear-completed" style="display: block;">
    Clear completed
  </button>
</footer>
```

## Technical Acceptance Criteria

+ [x] **`render_footer`** returns a  **`<footer>`** DOM element which can be rendered directly to the `document` or _nested_ in another DOM element.
+ [x]  **`<footer>`** contains:
  + [x] **`<span class="todo-count">`** which contains 
    + [x] a **`text`** node with: **"`{count}` item(s) left"**.
   _pseudocode_:
  `{model.todos.filter(done==false)}` item`{model.todo.length > 1 ? 's' : '' }` left
  + [x] **`<ul>`** containing 3 **`<li>`** with the following links (**`<a>`**):
    + [x] Show **`All`**: **`<a href="#/" class="selected">All</a>`**
      + [x] **`class="selected"`** should only appear on the selected menu/navigation item.
       this should be "driven" by the `model.hash` property.
    + [x] Show **`Active`**: **` <a href="#/active">Active</a>`**
    + [x] Show **`Completed`**: **`<a href="#/completed">Completed</a>`**
  + [x] **`<button class="clear-completed" style="display: block;">`** will **_Clear_ all `Completed`** items.
    _pseudocode_:
`var new_model =  model.todos.filter(function(item) { return item.done === false})`

This issue is part of the TodoMVC Feature List [Epic] #48

**Comment by nelsonic** [comment]
## `render_footer` Test

Here is a sample test you can add to your `test/todo-app.test.js` file:
(_if you feel confident in your TDD skills,
  you could **`try`** to write your own test/assertions..._)

```js
test.only('render_footer view using (elmish) HTML DOM functions', function (t) {
  const model = {
    todos: [
      { id: 1, title: "Learn Elm Architecture", done: true },
      { id: 2, title: "Build Todo List App",    done: false },
      { id: 3, title: "Win the Internet!",      done: false }
    ],
    hash: '#/' // the "route" to display
  };
  // render_footer view and append it to the DOM inside the `test-app` node:
  document.getElementById(id).appendChild(app.render_footer(model));

  // todo-count should display 2 items left (still to be done):
  const count = document.querySelectorAll('.todo-count')[0].textContent;
  t.equal(count, "2", "count of items left: " + count);

  // count number of footer <li> items:
  t.equal(document.querySelectorAll('li').length, 3, "3 <li> in <footer>");

  // check footer link text and href:
  const link_text = ['All', 'Active', 'Completed'];
  const hrefs = ['#/', '#/active', '#/completed'];
  document.querySelectorAll('a').forEach(function (a, index) {
    t.equal(item.textContent, model.todos[index].title,
      "index #" + index + " <label> text: " + item.textContent)
  });

  // check for "Clear completed" button in footer:
  const clear = document.querySelectorAll('.clear-completed')[0].textContent;
  t.equal(clear, 'Clear completed', '<button> in <footer> "Clear completed"');

  elmish.empty(document.getElementById(id)); // clear DOM ready for next test
  t.end();
});
```

![image](https://user-images.githubusercontent.com/194400/43774185-3be99666-9a40-11e8-9387-f172f95dd80b.png)

**Comment by nelsonic** [comment]
![render_footer-tests-passing-coverage-100percent](https://user-images.githubusercontent.com/194400/43776336-6a3b8fe0-9a47-11e8-8155-deb0fcf44e5a.png)

**Comment by nelsonic** [comment]
![counter-test-passing](https://user-images.githubusercontent.com/194400/45190621-ca7d7d80-b236-11e8-92b3-5a4fbda6f12a.png)
