### ISSUE TITLE
view function in Todo List App

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-elm-architecture-in-javascript#54]
Now that we have the individual ("_lower order_") functions 
**`render_main`** #51, **`render_item`** #52, and **`render_footer`** #53 
for rendering the _sections_ of the todo app,
we can write the `view` function to render the _entire_ app!

With the `main` and `footer` "_partial_" views built, the overall **`view`** is rediculously simple:

![todoapp-view](https://user-images.githubusercontent.com/194400/43779964-6fb92176-9a51-11e8-8b78-64c60242990d.png)

To save on repetition, and illustrate just how _simple_ the **`view`** is, this is the "HTML"
with the **`<section class"main">`** and **`<footer class="footer">`** partials replaced by invocations to the respective functions **`render_main`** #51 and **`render_footer`** #53:

```html
<section class="todoapp">
  <header class="header">
    <h1>todos</h1>
    <input class="new-todo" placeholder="What needs to be done?" autofocus="">
  </header>
  render_main(model)
  render_footer(model)
</section>
```

## Acceptance Criteria 

View displays:
+ [ ] **`<h1>`** containing the title text "**todos**".
+ [ ] **`<input class="new-todo">`** has placeholder text **"What needs to be done?"**
+ [ ] **`<ul class="todo-list">`** list of todo items has `zero` items by default.
+ [ ] `<footer>` count is Zero when the app is first rendered with no todos in the `model`.

**Comment by nelsonic** [comment]
![app.view-not-a-function](https://user-images.githubusercontent.com/194400/43782111-721805c2-9a56-11e8-970b-681b1499b3a8.png)

**Comment by nelsonic** [comment]
![image](https://user-images.githubusercontent.com/194400/43782895-48496f22-9a58-11e8-9fde-dbb5554f43a0.png)
