### ISSUE TITLE
Subscriptions: How to "Listen" for Events and What to do ...

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-elm-architecture-in-javascript#57]
# Todo
+ [ ] **investigate/research** if we need to register events _each_ time the DOM is re-rendered
+ [ ] **write** a ***test*** for **`subscriptions`** ... e.g: 
  + [ ] **`[Up]`** & **`[Down]`** keyboard key press increases/decreases the counter.
+ [ ] **add** **`subscriptions`** parameter to **`mount`** function 
+ [ ] ***invoke*** the  **`subscriptions`** in **`mount`** depending on the outcome of initial research

required for: https://github.com/dwyl/learn-elm-architecture-in-javascript/issues/55
