### ISSUE TITLE
DELETE a Todo List item using the "cross" (button)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-elm-architecture-in-javascript#59]
+ [x] should show the `<button class="destroy">` on hover (over the item)
+ [x] Clicking/tapping the `<button class="destroy">` sends the `signal('DELETE', todo.id)`
+ [x] `DELETE` update case receives the `todo.id` and removes it from the `model.todos` Array.

**Comment by nelsonic** [comment]
![toggle-todo-tests-passing](https://user-images.githubusercontent.com/194400/43992979-a4d00ab6-9d7e-11e8-891b-9f699f474dd5.png)
